name: school_schedule
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to
version: 1.0.0+1

environment:
    sdk: '>=2.16.1 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    google_fonts: ^2.3.1

    cupertino_icons: ^1.0.2
    flutter_svg: ^1.0.3
    social_login_buttons: ^1.0.6+2
    intl: ^0.17.0
    firebase_auth: ^3.1.4
    firebase_core: ^1.8.0
    font_awesome_flutter: ^9.2.0
    google_sign_in: ^5.2.0
    firebase_analytics: ^5.0.11
    animated_splash_screen: ^1.2.0
    cloud_firestore: ^3.1.12
    flutter_colorpicker: ^1.0.3
    table_calendar: ^3.0.6
    http: ^0.13.4

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/images/

    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins-Regular.ttf
              - asset: assets/fonts/Poppins-Bold.ttf
                weight: 900
              - asset: assets/fonts/Poppins-Light.ttf
                weight: 300
              - asset: assets/fonts/Poppins-Medium.ttf
                weight: 500
